name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      id: lint
      run: npm run lint
      
    - name: Check formatting with Prettier
      id: format
      run: npm run format:check
      
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: quality-check  # ESLintとPrettierが成功した場合のみ実行
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      id: build
      run: npm run build
      
    - name: Run tests
      id: test
      run: npm test
      continue-on-error: true  # テストが失敗してもアーティファクトをアップロード
      
    - name: Upload build artifacts
      if: steps.build.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: www/
        retention-days: 7
        
    - name: Test Summary
      if: always()
      run: |
        echo "## CI Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Step | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Build | ${{ steps.build.outcome }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Test | ${{ steps.test.outcome }} |" >> $GITHUB_STEP_SUMMARY